spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false;INIT=create schema if not exists test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: false
    continueOnError: true
  jooq:
    sql-dialect: H2
  h2:
    console:
      enabled: true
      path: /h2
  logging:
    level:
        ROOT: DEBUG

flyway:
  locations:
    - filesystem:src/main/resources/db/migration
  schemas:
    - public